#!/bin/bash

$HOME/.config/bspwm/autostart.sh &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          4

bspc config normal_border_color   "#2b3b51"
bspc config active_border_color   "#f4a261"
bspc config focused_border_color  "#719cd6"
bspc config presel_feedback_color "#81b29a"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -r "*"
bspc rule -a Google-chrome desktop='^2' follow=off
bspc rule -a mpv state=floating desktop='^3'
bspc rule -a Lxappearance state=floatinj
bspc rule -a "Kvantum Manager" state=floating
bspc rule -a qt5ct state=floating
bspc rule -a "VirtualBox Manager" state=fullscreen desktop="^4"
bspc rule -a "VirtualBox Machine" state=fullscreen desktop="^5"
