return {
	"nvim-treesitter/nvim-treesitter",
	name = "treesitter",
	dependencies = {
		"nvim-treesitter/nvim-treesitter-textobjects",
	},
	build = ":TSUpdate",
	config = function()
		require("nvim-treesitter.configs").setup({
			ensure_installed = {
				"angular",
				"bash",
				"gitattributes",
				"gitcommit",
				"git_config",
				"gitignore",
				"git_rebase",
				"go",
				"java",
				"javascript",
				"json",
				"json5",
				"lua",
				"markdown",
				"markdown_inline",
				"properties",
				"proto",
				"python",
				"rust",
				"sql",
				"tmux",
				"toml",
				"tsx",
				"typescript",
				"vim",
				"vimdoc",
				"yaml",
			},
			auto_install = true,
			highlight = { enable = true },
			indent = { enable = true },
			incremental_selection = {
				enable = true,
				keymaps = {
					init_selection = "<c-space>",
					node_incremental = "<c-space>",
					scope_incremental = "<c-s>",
					node_decremental = "<M-space>",
				},
			},
		})
	end,
}
