[font]
size = 10

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "BlexMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "BlexMono Nerd Font Mono"
style = "Medium Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Medium"
